FROM quay.io/centos/centos:stream9
RUN dnf -y install python3.12 python3.12-pip rust cargo \
 && ln -s /usr/bin/python3.12 /usr/bin/python \
 && rm -f /usr/bin/python3 \
 && ln -s /usr/bin/python3.12 /usr/bin/python3

WORKDIR /app

