FROM quay.io/centos/centos:stream9
RUN dnf -y install python3.12 python3.12-pip rust cargo \
 && alternatives --install /usr/bin/python python /usr/bin/python3.12 1 \
 && alternatives --install /usr/bin/python3 python3 /usr/bin/python3.12 1 \
 && mkdir /app

WORKDIR /app

