FROM quay.io/arcalot/arcaflow-plugin-baseimage-python-osbase:stream9

# Setup poetry
RUN python3.9 -m pip install poetry==1.4.2 \
 && python3.9 -m poetry config virtualenvs.create false


# Setup coverage
RUN python3.9 -m pip install coverage==7.2.7 \
 && mkdir /htmlcov
