FROM osbase-test

# Setup poetry
RUN python3.9 -m pip install poetry==1.4.2
RUN python3.9 -m poetry config virtualenvs.create false


# Setup coverage
RUN python3.9 -m pip install coverage==7.2.7
RUN mkdir /htmlcov
